### ISSUE TITLE
TypeError: async_setup_entry.<locals>.boto_client() missing 1 required positional argument: 'aws_config'

### ISSUE THREAD

**Issue by Ramias1** [robmarkcole/HASS-S3#39]
I've had this working on HassOS for probably over a year now.

Getting this error after recent update:

```
2024-07-22 09:58:19.384 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Personal AWS for s3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/s3/__init__.py", line 248, in async_setup_entry
    client = await hass.async_add_executor_job(boto_client, aws_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_setup_entry.<locals>.boto_client() missing 1 required positional argument: 'aws_config'
```

**Comment by robmarkcole** [comment]
Hmm.. I don't see anything obvious, @rcmachado worked on this recently, any ideas?

**Comment by rcmachado** [comment]
Thanks for flagging me, @robmarkcole.

There is an extra parameter (`self`) in `boto_client`:

https://github.com/robmarkcole/HASS-S3/blob/8bc01904a52cacf131bfcf35ceb00b26f305dc35/custom_components/s3/__init__.py#L245

I'll send a patch later today.
